# This Docker Compose file runs a PostgreSQL database, a PostgREST server connected to it,
# and a Swagger UI instance to visualize the API documentation.

version: '1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # For tests ONLY
    volumes:
      - ./init-api-db.sh:/docker-entrypoint-initdb.d/init-api-db.sh
      - apidb:/var/lib/postgresql/data:rw
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:authpass@db:5432/scarlet
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: anonymous
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://127.0.0.1:3000/
    depends_on:
      - db
volumes:
  apidb: